version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - unzip
    - wget
    - wine
  tools:
    python: mambaforge-4.10
  jobs:
    pre_install:
      - wget https://github.com/LAStools/LAStools.github.io/raw/master/download/LAStools_210628.zip
      - unzip LAStools_210628.zip
      - mkdir -p ~/.ssh
      # We are running into https://github.com/readthedocs/readthedocs.org/issues/8636. Therefore,
      # we absolutely need to elimiate the single quotes.
      - ./doc/rtd-write-ssh.py
      - cat ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - echo "ssc-jupyter.iwr.uni-heidelberg.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJlEBwr7Qv0expAPxukZOmIUcVI1erVPya+GkzCd+iQK" >> ~/.ssh/known_hosts
      - scp -P 22222 ssc-github@ssc-jupyter.iwr.uni-heidelberg.de:/home/ssc-github/opals_2.5.0_linux64.tar.gz .
      - tar xzvf opals_2.5.0_linux64.tar.gz

sphinx:
  builder: html
  configuration: doc/source/conf.py

conda:
  environment: doc/environment-rtd.yml

formats:
  - htmlzip
