version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10

sphinx:
  builder: singlehtml
  configuration: doc/source/conf.py

conda:
  environment: environment.yml

formats:
  - htmlzip
