name: afwizard-rtd
channels:
  - conda-forge
dependencies:
  - python
  - afwizard-library
  - click
  - gdal
  - geojson
  - IPython
  - ipyfilechooser
  - ipyleaflet
  - ipywidgets>=8
  - ipywidgets-jsonschema
  - jsonmerge
  - jsonschema<4
  - jupyter-resource-usage
  - jupyterlab
  - pdal
  - pooch
  - pyproj
  - pyrsistent
  - python-pdal
  - pytools
  - pillow
  - wrapt
  - xdg
  - xmltodict
  - pip
  - pip:
    - m2r2
    - nbsphinx
    - nbsphinx-link
    - sphinx-click
    - geojson-rewind
