name: afwizard-rtd
channels:
  - conda-forge
  - conda-forge/label/ipywidgets_rc
  - conda-forge/label/jupyterlab_widgets_rc
  - conda-forge/label/widgetsnbextension_rc
dependencies:
  - python
  - afwizard-library
  - click
  - gdal
  - geojson
  - IPython
  - ipyfilechooser
  - ipyleaflet
  - ipywidgets=8.0.0rc0
  - ipywidgets-jsonschema
  - jsonmerge
  - jsonschema<4
  - jupyter-resource-usage
  - jupyterlab
  - pdal
  - pyproj
  - pyrsistent
  - python-pdal
  - pytools
  - pillow
  - wrapt
  - xdg
  - xmltodict
  - pip
  - pip:
    - m2r2
    - nbsphinx
    - nbsphinx-link
    - sphinx-click
